language: python
python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2
  - 3.3
script: python tests/tests.py
install:
  - pip install requests pygments
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi"

