language: python
python:
  - 2.6
  - 2.7
  # TODO: Python 3
  #- 3.2
script: python tests.py
install:
  - pip install requests pygments
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi"

